#!/bin/bash
set -e

# Turso Setup Script for UpNews
# This script provisions a Turso edge SQLite database and generates environment variables

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
DB_NAME="${1:-upnews-db}"
ORG_NAME="${2:-default}"
OUTPUT_FILE=".env.turso"

echo -e "${YELLOW}UpNews Turso Database Setup${NC}"
echo "=============================="

# Check if turso CLI is installed
if ! command -v turso &> /dev/null; then
    echo -e "${RED}Error: turso CLI is not installed${NC}"
    echo "Install from: https://docs.turso.tech/tutorials/get-started-turso-cli"
    exit 1
fi

echo -e "${GREEN}✓ turso CLI found${NC}"

# Check if user is authenticated
if ! turso auth whoami &> /dev/null; then
    echo -e "${YELLOW}Authenticating with Turso...${NC}"
    turso auth login
fi

echo -e "${GREEN}✓ Authenticated with Turso${NC}"

# Create database
echo -e "${YELLOW}Creating Turso database: $DB_NAME${NC}"
if turso db create "$DB_NAME" --org "$ORG_NAME" 2>/dev/null; then
    echo -e "${GREEN}✓ Database created: $DB_NAME${NC}"
else
    echo -e "${YELLOW}Database already exists or error: $DB_NAME${NC}"
fi

# Get database credentials
echo -e "${YELLOW}Retrieving database credentials...${NC}"
DB_URL=$(turso db show "$DB_NAME" --org "$ORG_NAME" | grep "URL" | awk '{print $NF}')
DB_TOKEN=$(turso db tokens create "$DB_NAME" --org "$ORG_NAME" 2>/dev/null | tail -1)

if [ -z "$DB_URL" ] || [ -z "$DB_TOKEN" ]; then
    echo -e "${RED}Error: Could not retrieve database credentials${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Credentials retrieved${NC}"

# Initialize schema (if schema.sql exists)
if [ -f "schema.sql" ]; then
    echo -e "${YELLOW}Initializing database schema...${NC}"
    turso db shell "$DB_NAME" < schema.sql
    echo -e "${GREEN}✓ Schema initialized${NC}"
else
    echo -e "${YELLOW}No schema.sql found, skipping initialization${NC}"
    echo "Create a schema.sql file and run: turso db shell $DB_NAME < schema.sql"
fi

# Write environment variables
cat > "$OUTPUT_FILE" << EOF
# Turso Database Configuration (generated by turso-setup.sh)
# Generated: $(date)

TURSO_URL="$DB_URL"
TURSO_TOKEN="$DB_TOKEN"
DATABASE_URL="$DB_URL"

# For local development, use SQLite:
# DATABASE_URL="sqlite:///./upnews.db"

# For production, uncomment above and use Turso connection string

# Free tier limits:
# - 500 databases
# - Unlimited reads on all subscriptions
# - Generous write quotas
# - Pay-as-you-go after free tier

# Pricing:
# - Free: $0/mo (with limits)
# - Pro: $29/mo (unlimited)

# Docs: https://docs.turso.tech/
EOF

echo -e "${GREEN}✓ Environment file created: $OUTPUT_FILE${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "1. Copy variables to your .env file:"
echo "   cat $OUTPUT_FILE >> .env"
echo ""
echo "2. Verify connection:"
echo "   turso db shell $DB_NAME"
echo ""
echo "3. Update docker-compose.yml to use TURSO_URL"
echo ""
echo "4. For production deployment, set GitHub Secrets:"
echo "   - TURSO_URL=$DB_URL"
echo "   - TURSO_TOKEN=***"
echo ""
echo -e "${GREEN}Setup complete!${NC}"
